# Generated by Django 4.0.5 on 2022-08-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='userBid',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='lot',
            name='bid',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
