# Generated by Django 4.0.5 on 2022-08-02 19:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_bids_userbid_alter_lot_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='usersWhoAddToWatchlist',
            field=models.ManyToManyField(blank=True, related_name='watchingUsers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
