# Generated by Django 4.0.5 on 2022-08-03 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_lot_userswhoaddtowatchlist_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
