# Generated by Django 4.0.5 on 2022-08-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_lot_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='statusActive',
            field=models.BooleanField(default=True),
        ),
    ]
