# Generated by Django 4.0.5 on 2022-08-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_lot_dirtyhack'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='dirtyHack',
            field=models.BooleanField(default=False),
        ),
    ]
